require('dotenv').config();

var CONFIG: any = {};

CONFIG.PORT = process.env.PORT || 3000;
CONFIG.APP_ENV = process.env.APP_ENV || 'development';

CONFIG.SESSION_SECRET = process.env.SESSION_SECRET;

CONFIG.SENDGRID_EMAIL_API_KEY = process.env.SENDGRID_EMAIL_API_KEY;

CONFIG.GOOGLE_CONSUMER_KEY = process.env.GOOGLE_CONSUMER_KEY;
CONFIG.GOOGLE_CONSUMER_SECRET = process.env.GOOGLE_CONSUMER_SECRET;
CONFIG.GOOGLE_CALLBACK_URL = process.env.GOOGLE_CALLBACK_URL;

CONFIG.FIREBASE_ACCOUNT_TYPE = process.env.FIREBASE_ACCOUNT_TYPE || 'service_account';
CONFIG.FIREBASE_PROJECT_ID = process.env.FIREBASE_PROJECT_ID;
CONFIG.FIREBASE_PRIVATE_KEY_ID = process.env.FIREBASE_PRIVATE_KEY_ID;
CONFIG.FIREBASE_PRIVATE_KEY = process.env.FIREBASE_PRIVATE_KEY?.replace(/\\n/g, '\n');
CONFIG.FIREBASE_CLIENT_EMAIL = process.env.FIREBASE_CLIENT_EMAIL;
CONFIG.FIREBASE_CLIENT_ID = process.env.FIREBASE_CLIENT_ID;
CONFIG.FIREBASE_AUTH_URI =
  process.env.FIREBASE_AUTH_URI || 'https://accounts.google.com/o/oauth2/auth';
CONFIG.FIREBASE_TOKEN_URI =
  process.env.FIREBASE_TOKEN_URI || 'https://accounts.google.com/o/oauth2/auth';
CONFIG.FIREBASE_AUTH_PROVIDER_x509_CERT_URL =
  process.env.FIREBASE_AUTH_PROVIDER_x509_CERT_URL || 'https://www.googleapis.com/oauth2/v1/certs';
CONFIG.FIREBASE_CLIENT_x509_CERT_URL = process.env.FIREBASE_CLIENT_x509_CERT_URL;

export default CONFIG;
