require('dotenv').config();

const CONFIG: any = {};

CONFIG.PORT = process.env.PORT || 3000;
CONFIG.APP_ENV = process.env.APP_ENV || 'development';

CONFIG.RESEND_EMAIL_API_KEY = process.env.RESEND_EMAIL_API_KEY;

CONFIG.FIREBASE_ACCOUNT_TYPE = process.env.FIREBASE_ACCOUNT_TYPE;
CONFIG.FIREBASE_PROJECT_ID = process.env.FIREBASE_PROJECT_ID;
CONFIG.FIREBASE_PRIVATE_KEY_ID = process.env.FIREBASE_PRIVATE_KEY_ID;
CONFIG.FIREBASE_PRIVATE_KEY = process.env.FIREBASE_PRIVATE_KEY?.replace(/\\n/g, '\n');
CONFIG.FIREBASE_CLIENT_EMAIL = process.env.FIREBASE_CLIENT_EMAIL;
CONFIG.FIREBASE_CLIENT_ID = process.env.FIREBASE_CLIENT_ID;
CONFIG.FIREBASE_AUTH_URI = process.env.FIREBASE_AUTH_URI;
CONFIG.FIREBASE_TOKEN_URI = process.env.FIREBASE_TOKEN_URI;
CONFIG.FIREBASE_AUTH_PROVIDER_X509_CERT_URL = process.env.FIREBASE_AUTH_PROVIDER_X509_CERT_URL;
CONFIG.FIREBASE_CLIENT_X509_CERT_URL = process.env.FIREBASE_CLIENT_X509_CERT_URL;

export default CONFIG;
